---
title: "HW-02: Shot Charts"
author: "Phoebe Abramowitz"
date: "3/4/2018"
output: github_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, fig.path='../images')
library(dpylr)
```
## Question 5.1
```{r setup, include=FALSE}
#do I need to oo the knitr thing everytime?
#should I instead be pulling shots-data from the previous script? not sure how to do that in R
shots_data <- read.csv('../data/shots-data.csv')
shots_data

#group by player name and count number of shots 
player_shot_count<- count(shots_data, name, sort=TRUE)
psc <- rename(player_shot_count,total=n)
psc
```
## Question 5.2
```{r}
#effective shooting percent by player
efctv_shot_count<- rename(count(filter(shots_data, shot_made_flag=="made shot"), 
                                name), made=n)
comb <- left_join(psc,efctv_shot_count)
shooting_perc <- arrange(mutate(comb, perc_made=(made/total)),desc(perc_made))



shots_data_2pt <- filter(shots_data, shot_type=="2PT Field Goal")
psc_2pt <- rename(count(shots_data_2pt,name, sort=TRUE),total=n)

efctv_shot_count_2pt<- rename(count(filter(shots_data_2pt, shot_made_flag=="made shot"),
                                    name), made=n)
comb_2pt <- left_join(psc_2pt,efctv_shot_count_2pt)
shooting_perc_2pt <- arrange(mutate(comb_2pt, perc_made=(made/total)),desc(perc_made))


shots_data_3pt <- filter(shots_data, shot_type=="3PT Field Goal")
psc_3pt <- rename(count(shots_data_3pt,name, sort=TRUE),total=n)

efctv_shot_count_3pt<- rename(count(filter(shots_data_3pt, shot_made_flag=="made shot"),
                                    name), made=n)
comb_3pt <- left_join(psc_3pt,efctv_shot_count_3pt)
shooting_perc_3pt <- arrange(mutate(comb_3pt, perc_made=(made/total)),desc(perc_made))


shooting_perc_2pt
shooting_perc_3pt
shooting_perc
```
## Question 6
```{r}
#dWHy am I getting numbers >1 here? Only for distance values above 33, which is very big
shots_data_dist <-mutate(shots_data,shot_distance=round(sqrt(x^2+y^2)))
                        
dist_shot_count <- count(shots_data, shot_distance)
dsc <- arrange(rename(dist_shot_count,total=n),shot_distance)
#this next is giving values greater than the general count, do we have some shots without
#distance values?
efctv_shot_dist<-count(filter(shots_data_dist, shot_made_flag=="made shot"),
                                shot_distance)
comb_dist <- left_join(dsc,efctv_shot_dist)
shooting_perc_dist <- arrange(mutate(comb_dist, 
                                     made_shot_prop=(n/total)))
spd <- select(shooting_perc_dist,shot_distance,made_shot_prop)
spd
```
```{r}
ggplot(data=spd)+
  geom_point(aes(x=shot_distance,y=made_shot_prop),color="blue")+
  ggtitle("Proportion of shots made by distance")
```
This appears to confirm the opposite, ask in OH
## Question 7


